# ----------- CONFIGURABLE START -----------
title:            "Project-Blog"
description:      "개발일지"
url:              http://portfl.tk/ # 域名
signoff:          "Project-Blog" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         HOME
    url:          /
    external:     false
  - name:         DevNote
    url:          /book
    external:     false
  - name:         ARCHIVES
    url:          /archives
    external:     false
  - name:         TAGS
    url:          /tags
    external:     false
  - name:         ABOUT
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
